/**
 * Test: Verifikasi trigger SAK EP (generate_sak_ep_journal_entries)
 * Jalankan: node db/test-trigger.js
 */
require('dotenv').config({ path: '.env.local' });
const { Pool } = require('@neondatabase/serverless');

const pool = new Pool({ connectionString: process.env.NEON_DATABASE_URL, max: 2 });

async function run() {
  const client = await pool.connect();
  try {
    // 1. Get tenant
    const tenant = await client.query('SELECT id, name FROM tenants LIMIT 1');
    const tid = tenant.rows[0].id;
    console.log('=== TEST TRIGGER SAK EP ===');
    console.log('Tenant:', tenant.rows[0].name, '(' + tid + ')');

    // 2. Insert daily_closing (trigger should fire)
    await client.query('BEGIN');
    await client.query(`SELECT set_config('app.current_tenant_id', $1, true)`, [tid]);

    const closing = await client.query(
      `INSERT INTO daily_closings (tenant_id, cash_on_hand, notes)
       VALUES ($1, 250000, 'Test trigger SAK EP - verifikasi otomatis')
       RETURNING id, closed_at, cash_on_hand`,
      [tid]
    );
    await client.query('COMMIT');
    console.log('\n✓ Daily closing created:', closing.rows[0]);

    // 3. Check ledger entries generated by trigger
    const ledger = await client.query(
      `SELECT le.id, a.code, a.name AS account_name, le.debit, le.credit,
              encode(le.prev_hash, 'hex') AS prev_hash_hex,
              encode(le.row_hash, 'hex') AS row_hash_hex
       FROM ledger_entries le
       JOIN accounts a ON a.id = le.account_id
       WHERE le.tenant_id = $1
       ORDER BY le.id DESC
       LIMIT 4`,
      [tid]
    );

    if (ledger.rows.length >= 2) {
      console.log('\n✓ Trigger SAK EP BERHASIL — Jurnal ganda tercipta:');
      ledger.rows.forEach((row, i) => {
        const type = Number(row.debit) > 0 ? 'DEBIT' : 'KREDIT';
        const amount = Number(row.debit) > 0 ? row.debit : row.credit;
        console.log(`  [${i + 1}] ${type} ${row.code} ${row.account_name}: Rp${Number(amount).toLocaleString('id-ID')}`);
        console.log(`      Hash: ${row.row_hash_hex.slice(0, 16)}...`);
      });
    } else {
      console.log('\n✗ GAGAL — Tidak ada ledger entries tercipta. Trigger mungkin belum aktif.');
    }

    // 4. Verify hash chain linkage
    if (ledger.rows.length >= 2) {
      const newest = ledger.rows[0];
      const second = ledger.rows[1];
      const linked = newest.prev_hash_hex === second.row_hash_hex;
      console.log('\n' + (linked ? '✓' : '✗') + ' Hash chain linkage:', linked ? 'VALID' : 'BROKEN');
    }

    // 5. Check accounts auto-created
    const accounts = await client.query(
      `SELECT code, name, type FROM accounts WHERE tenant_id = $1 ORDER BY code`,
      [tid]
    );
    console.log('\n✓ Accounts for tenant:');
    accounts.rows.forEach((a) => console.log(`  ${a.code} — ${a.name} (${a.type})`));

  } catch (e) {
    await client.query('ROLLBACK').catch(() => {});
    console.error('\n✗ Error:', e.message);
  } finally {
    client.release();
    await pool.end();
  }
}

run();
